# PostgreSQL. Versions 8.2 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: vagadetotes_development

test:
  <<: *default
  database: vagadetotes_test

production:
  <<: *default
  database: <%= ENV['VAGADETOTES_DATABASE'] %>
  username: <%= ENV['VAGADETOTES_USER'] %>
  password: <%= ENV['VAGADETOTES_PASSWORD'] %>
  host:     <%= ENV['VAGADETOTES_HOST'] %>
  port:     <%= ENV['VAGADETOTES_PORT'] %>
